apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: smart-education-frontend-config
  namespace: smart-education
spec:
  redirectToHttps:
    enabled: true
    responseCodeName: MOVED_PERMANENTLY_DEFAULT
