apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: smart-education
  labels:
    app.kubernetes.io/name: smart-education-frontend
    app.kubernetes.io/component: web
    app.kubernetes.io/part-of: smart-education-portal
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: smart-education-frontend
    app.kubernetes.io/component: web
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
